name: Nightly Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: nightly-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pybind_tests:
    name: Run Deltakit-Stim Python bindings tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out main code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Package synchronisation
        run: uv sync --python 3.13 --resolution highest --group test
      - name: Test bindings
        run: uv run --python 3.13 --no-sync pytest
      # - name: Run failing binding tests
      #   run: |
      #     uv run --python 3.13 --no-sync pytest src/stim/simulators/frame_simulator_pybind_test.py
      #     uv run --python 3.13 --no-sync pytest src/stim/stabilizers/tableau_pybind_test.py
      #     uv run --python 3.13 --no-sync pytest src/stim/util_top/export_qasm_pybind_test.py
