name: Publish Deltakit-Stim

name: Build and publish wheels
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ${{ matrix.os_dist.os }}
    strategy:
      fail-fast: true
      matrix:
        os_dist: [
          {os: ubuntu-24.04, dist: cp310-manylinux_x86_64},
          {os: ubuntu-24.04, dist: cp311-manylinux_x86_64},
          {os: ubuntu-24.04, dist: cp312-manylinux_x86_64},
          {os: ubuntu-24.04, dist: cp313-manylinux_x86_64},
          {os: ubuntu-24.04, dist: cp314-manylinux_x86_64},

          {os: macos-14, dist: cp310-macosx_x86_64, macosarch: x86_64},
          {os: macos-14, dist: cp311-macosx_x86_64, macosarch: x86_64},
          {os: macos-14, dist: cp312-macosx_x86_64, macosarch: x86_64},
          {os: macos-14, dist: cp313-macosx_x86_64, macosarch: x86_64},
          {os: macos-14, dist: cp314-macosx_x86_64, macosarch: x86_64},

          {os: macos-14, dist: cp310-macosx_arm64, macosarch: arm64},
          {os: macos-14, dist: cp311-macosx_arm64, macosarch: arm64},
          {os: macos-14, dist: cp312-macosx_arm64, macosarch: arm64},
          {os: macos-14, dist: cp313-macosx_arm64, macosarch: arm64},
          {os: macos-14, dist: cp314-macosx_arm64, macosarch: arm64},
        ]
    env:
      CIBW_BUILD: "${{ matrix.os_dist.dist }}"
      CIBW_ARCHS_MACOS: "${{ matrix.os_dist.macosarch }}"
      # Optional: Configure repair command to handle deployment target issues
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
        delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}
        --ignore-missing-dependencies
      ### Skip tests
      # CIBW_TEST_REQUIRES: cirq-core pytest
      # CIBW_TEST_COMMAND: pytest {project}/src {project}/glue/cirq && stim help
    steps:
      - name: Check out Deltakit-Stim main code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
      - name: Install dependencies for wheel building
        run: pip install pybind11 cibuildwheel setuptools wheel
      - name: Build the wheel
        run: |
          python -m cibuildwheel --print-build-identifiers
          python -m cibuildwheel --output-dir dist
      # - name: Publish to PyPI
      #     uses: pypa/gh-action-pypi-publish@release/v1
      # - name: Confirm deployment
      #     timeout-minutes: 5
      #     run: |
      #       VERSION=${GITHUB_REF#refs/tags/v}
      #       until pip download maximum-independent-set==$VERSION
      #       do
      #           echo "Failed to download from PyPI, will wait for upload and retry."
      #           sleep 1
      #       done
